# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=20, null=True)),
                ('published_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['published_time'],
            },
        ),
    ]
