# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mypost_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='post_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
