# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170928_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
