# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170919_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypost',
            old_name='post_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='mypost',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='mypost',
            old_name='post_tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='mypost',
            old_name='post_title',
            new_name='title',
        ),
    ]
