# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170919_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypost',
            options={'ordering': ['title']},
        ),
    ]
