# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170920_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypost',
            options={'ordering': ['published_time']},
        ),
    ]
