# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170921_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypost',
            options={'ordering': ['title']},
        ),
    ]
